services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: [ "streamlit", "run", "app.py" ]
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true

  test:
    build:
      context: .
    volumes:
      - .:/app
    entrypoint: [ "python", "-m", "unittest", "discover", "-s", "tests" ]
