services:
  app:
    build:
      context: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src/
    #       target: /app/src/
    #     - action: sync
    #       path: ./app.py
    #       target: /app/app.py
    command: [ "streamlit", "run", "app.py" ]
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true

  test:
    build:
      context: .
    volumes:
      - .:/app
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src/
    #       target: /app/src/
    #     - action: sync
    #       path: ./tests
    #       target: /app/tests/
    entrypoint: [ "python", "-m", "unittest", "discover", "-s", "tests" ]
