name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Dependencies (Docker & Compose)
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Images
      run: |
        docker-compose build --parallel

    - name: Run Tests
      run: docker-compose run --rm test

    - name: Stop and Clean Up Containers
      if: always()
      run: docker-compose down --volumes --remove-orphans
