name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Dependencies (Docker & Compose)
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Cache Docker Layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker Images (With Cache)
      run: |
        docker-compose build --parallel \
          --cache-from=type=local,src=/tmp/.buildx-cache \
          --cache-to=type=local,dest=/tmp/.buildx-cache,mode=max

    - name: Run Tests Inside the Container
      run: docker-compose run --rm test

    - name: Stop and Clean Up Containers
      if: always()
      run: docker-compose down --volumes --remove-orphans
